#!/usr/bin/env bash

FTCCL_MIDWARE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FTCCL_REPO_ROOT="$(cd "${FTCCL_MIDWARE_DIR}/.." && pwd)"
FTCCL_HOME="${FTCCL_HOME:-${FTCCL_REPO_ROOT}/custom-rccl-dtk-26.04/build}"
HIP_PATH="${HIP_PATH:-/public/software/compiler/dtk-26.04/hip}"
CONDA_FTCCL_LIB="${CONDA_PREFIX:-/public/home/scnethpc26107/.conda/envs/ftccl}/lib"

export LD_LIBRARY_PATH="${CONDA_FTCCL_LIB}:${FTCCL_HOME}:${FTCCL_HOME}/lib:${FTCCL_HOME}/lib64:${HIP_PATH}/lib:${HIP_PATH}/../lib:${LD_LIBRARY_PATH:-}"
export LD_PRELOAD="${FTCCL_MIDWARE_DIR}/build/libftccl_midware.so${LD_PRELOAD:+:${LD_PRELOAD}}"
export PYTHONPATH="${FTCCL_MIDWARE_DIR}/python:${PYTHONPATH:-}"

export NCCL_ALGO="${NCCL_ALGO:-RING}"
export NCCL_PROTO="${NCCL_PROTO:-SIMPLE}"
export NCCL_CCLD_ENABLE="${NCCL_CCLD_ENABLE:-1}"
export NCCL_COLLNET_ENABLE="${NCCL_COLLNET_ENABLE:-0}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING="${TORCH_NCCL_ASYNC_ERROR_HANDLING:-0}"
export NCCL_ASYNC_ERROR_HANDLING="${NCCL_ASYNC_ERROR_HANDLING:-0}"

export FTCCL_BYPASS_ENABLE="${FTCCL_BYPASS_ENABLE:-1}"
export FTCCL_BYPASS_DIR="${FTCCL_BYPASS_DIR:-/tmp/ftccl_bypass}"
export FTCCL_BYPASS_WORLD_SIZE="${FTCCL_BYPASS_WORLD_SIZE:-8}"
export FTCCL_BYPASS_DEAD_RANK="${FTCCL_BYPASS_DEAD_RANK:-7}"
export FTCCL_BYPASS_VICTIM_MODE="${FTCCL_BYPASS_VICTIM_MODE:-noop}"
export FTCCL_BYPASS_TIMEOUT_SEC="${FTCCL_BYPASS_TIMEOUT_SEC:-30}"
export FTCCL_LOG_LEVEL="${FTCCL_LOG_LEVEL:-1}"

export FTCCL_DETECT_ENABLE="${FTCCL_DETECT_ENABLE:-1}"
export FTCCL_DETECT_CCLD_ENABLE="${FTCCL_DETECT_CCLD_ENABLE:-1}"
export FTCCL_DETECT_CCLD_MAX_CHANNELS="${FTCCL_DETECT_CCLD_MAX_CHANNELS:-64}"
export FTCCL_DETECT_TIMEOUT_MS="${FTCCL_DETECT_TIMEOUT_MS:-5000}"
export FTCCL_DETECT_POLL_USEC="${FTCCL_DETECT_POLL_USEC:-1000}"
export FTCCL_DETECT_MARK_KILLED="${FTCCL_DETECT_MARK_KILLED:-1}"
export FTCCL_DETECT_PROPAGATE_ERROR="${FTCCL_DETECT_PROPAGATE_ERROR:-1}"
export FTCCL_DETECT_RUN_ID="${FTCCL_DETECT_RUN_ID:-ftccl-$(date +%s)-$$}"

export FTCCL_PATCH_ENABLE="${FTCCL_PATCH_ENABLE:-1}"
export FTCCL_PATCH_LOG_LEVEL="${FTCCL_PATCH_LOG_LEVEL:-1}"
export FTCCL_PATCH_GLOBAL_BATCH_SIZE_AFTER_BYPASS="${FTCCL_PATCH_GLOBAL_BATCH_SIZE_AFTER_BYPASS:-126}"
export FTCCL_PATCH_VICTIM_DATA_MODE="${FTCCL_PATCH_VICTIM_DATA_MODE:-keep}"
export FTCCL_PATCH_GRAD_COMPENSATION="${FTCCL_PATCH_GRAD_COMPENSATION:-survivor_global_batch}"

mkdir -p "$FTCCL_BYPASS_DIR"
